In [1]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "../")))

from database_operations import DatabaseOperations
from overtake_model import OvertakingModel
from race_data import RaceDataSetup
from race_dataframe import RaceDataframe
from race_sim import RaceSimulation
from evaluation import RaceSimEvaluation, EvaluateMany

import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', None)

In [2]:
db1 = DatabaseOperations(2024, "Mexico City")
race1 = RaceDataframe(db1)
race_data1 = RaceDataSetup(db1, race1)
overtake1 = OvertakingModel(race1.race_df)
test = overtake1.get_model_accuracy()[1]

In [3]:
# race1.race_df[race1.race_df["lap_num"]>69]

In [4]:
# print(race_data1.driver_tyre_coefficients)

race_sim = RaceSimulation(race_data1, overtake1)
race_sim.simulate()
print(race_sim.num_overtakes)
sim_df = race_sim.get_results_as_dataframe()
sim_df

[2, 3, 4, 5, 6]
102

,driver_number,driver_name,pit_schedule,tyre_type,lap_num,sector,sector_time,stint_lap,cumulative_time,gap,pit,pace,position,starting_pos,base_sector_times,tyre_diff,stint_laps_diff,drs_available,retired,predicted_overtake
0,55,Carlos Sainz,"{33: 3, 1: 2}",3,71,3,20.680441,39,6290.724579,0.000000,False,32.662800,1,1,"{1: 27.037, 2: 29.296, 3: 19.533}",0,1,False,False,False
1,4,Lando Norris,"{31: 3, 1: 2}",3,71,3,20.724588,41,6301.600440,10.875861,False,20.791609,2,2,"{1: 27.204, 2: 29.191, 3: 19.67}",0,-2,False,False,False
2,16,Charles Leclerc,"{32: 3, 70: 1, 1: 2}",1,71,3,22.295508,2,6316.006178,14.405738,False,21.681420,3,3,"{1: 27.069, 2: 29.429, 3: 19.693}",2,39,False,False,False
3,81,Oscar Piastri,"{40: 3, 1: 2}",3,71,3,20.764084,32,6325.575423,9.569245,False,20.815996,4,8,"{1: 27.376, 2: 29.546, 3: 20.006}",-2,-30,False,False,False
4,44,Lewis Hamilton,"{29: 3, 1: 2}",3,71,3,20.884135,43,6336.953770,11.378347,False,20.953012,5,4,"{1: 27.295, 2: 29.546, 3: 19.688}",0,-11,False,False,False
5,1,Max Verstappen,"{27: 3, 1: 2}",3,71,3,20.837963,45,6349.997383,13.043613,False,20.910840,6,6,"{1: 27.222, 2: 29.318, 3: 19.631}",0,-2,False,False,False
6,63,George Russell,"{32: 3, 1: 2}",3,71,3,21.007904,40,6350.678434,0.681051,False,21.042683,7,5,"{1: 27.361, 2: 29.263, 3: 19.624}",0,5,True,False,False
7,20,Kevin Magnussen,"{31: 3, 1: 2}",3,71,3,21.060715,41,6360.511486,9.833052,False,21.102734,8,7,"{1: 27.272, 2: 29.624, 3: 19.854}",0,-1,False,False,False
8,27,Nico Hulkenberg,"{30: 3, 1: 2}",3,71,3,20.877154,42,6370.565555,10.054068,False,20.955780,9,9,"{1: 27.382, 2: 29.592, 3: 19.841}",0,-1,False,False,False
9,45,Franco Colapinto,"{48: 2, 1: 3}",2,71,3,21.153774,24,6382.799964,12.234410,False,21.188880,10,12,"{1: 27.769, 2: 29.832, 3: 19.936}",1,18,False,False,False
10,31,Esteban Ocon,"{1: 3, 49: 2}",2,71,3,21.073116,23,6382.840408,0.040444,False,21.111011,11,13,"{1: 27.658, 2: 29.887, 3: 20.072}",0,1,True,False,False
11,40,Liam Lawson,"{40: 2, 66: 1, 1: 3}",1,71,3,22.216681,6,6383.892847,1.052439,False,21.294256,12,16,"{1: 27.636, 2: 29.64, 3: 19.833}",1,17,False,False,False
12,18,Lance Stroll,"{27: 3, 1: 2}",3,71,3,20.834588,45,6388.522148,4.629301,False,20.914056,13,11,"{1: 27.504, 2: 29.848, 3: 19.873}",-2,-39,False,False,False
13,10,Pierre Gasly,"{29: 3, 1: 2}",3,71,3,21.036346,43,6392.186444,3.664296,False,21.102913,14,10,"{1: 27.418, 2: 29.585, 3: 19.847}",0,2,False,False,False
14,77,Valtteri Bottas,"{50: 2, 1: 3}",2,71,3,21.295035,22,6397.531882,5.345438,False,21.243419,15,14,"{1: 27.697, 2: 29.811, 3: 19.885}",1,21,False,False,False
15,11,Sergio Perez,"{21: 2, 44: 2, 69: 1, 1: 3}",1,71,3,20.385993,3,6415.984148,18.452266,False,20.824106,16,17,"{1: 27.555, 2: 29.859, 3: 20.124}",1,19,False,False,False
16,24,Guanyu Zhou,"{44: 2, 1: 3}",2,71,3,21.153108,28,6422.196984,6.212836,False,21.196049,17,15,"{1: 27.746, 2: 30.217, 3: 20.109}",-1,-25,False,False,False
17,23,Alexander Albon,{1: 2},2,71,0,0.000000,71,0.000000,0.000000,False,0.000000,998,19,"{1: 27.344, 2: 29.58, 3: 19.855}",0,0,False,True,NaN
18,22,Yuki Tsunoda,{1: 2},2,71,0,0.000000,71,0.000000,0.000000,False,0.000000,998,20,"{1: 27.446, 2: 29.758, 3: 19.7}",0,0,False,True,NaN
19,14,Fernando Alonso,{1: 2},2,71,3,23.318879,71,1493.686362,3.634246,False,23.295926,999,18,"{1: 27.463, 2: 29.665, 3: 19.898}",0,0,False,True,False

In [5]:
eval = RaceSimEvaluation(race_sim, race1, db1)

print(eval.compare_total_cumulative_times()[1])
eval.compare_total_cumulative_times()[0]

293.25630198719506

,driver_number,driver_name,simulated_cumulative_time,actual_cumulative_time,absolute_error
0,55,Carlos Sainz,6290.724579,6023.912,266.812579
1,4,Lando Norris,6301.600440,6028.139,273.461440
2,16,Charles Leclerc,6316.006178,6057.475,258.531178
3,81,Oscar Piastri,6325.575423,6083.971,241.604423
4,44,Lewis Hamilton,6336.953770,6067.579,269.374770
5,1,Max Verstappen,6349.997383,6083.463,266.534383
6,63,George Russell,6350.678434,6071.151,279.527434
7,20,Kevin Magnussen,6360.511486,6086.111,274.400486
8,27,Nico Hulkenberg,6370.565555,6024.711,345.854555
9,45,Franco Colapinto,6382.799964,6047.376,335.423964
10,31,Esteban Ocon,6382.840408,6053.418,329.422408
11,40,Liam Lawson,6383.892847,6085.804,298.088847
12,18,Lance Stroll,6388.522148,6045.905,342.617148
13,10,Pierre Gasly,6392.186444,5959.340,432.846444
14,77,Valtteri Bottas,6397.531882,6062.091,335.440882
15,11,Sergio Perez,6415.984148,6093.613,322.371148
16,24,Guanyu Zhou,6422.196984,6081.243,340.953984
17,23,Alexander Albon,0.000000,NaN,NaN
18,22,Yuki Tsunoda,0.000000,NaN,NaN
19,14,Fernando Alonso,1493.686362,1428.339,65.347362

In [6]:
eval.get_position_accuracy_final_class()

{'position_accuracy': 0.29411764705882354,
 'top_3_accuracy': 1.0,
 'mean_error': 1.5294117647058822,
 'total_error': 26}

In [7]:
eval.compare_total_to_front()

[14, 23, 22]
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70}
70

{'total_simulated_gap_to_front': 1226.2502293036769,
 'total_actual_gap_to_front': 1272.1519999999973}